<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import type { Employee, EmployeeId } from '../../app/workspace';
import { useI18n } from '../../app/i18n';
import { baselineWorkspaceSkillMeta } from '../../app/baseline-skills';
import { useCapabilities, type PolicyMode } from '../../app/capabilities';

const props = defineProps<{ employees: Employee[]; selectedEmployeeId: EmployeeId }>();
const emit = defineEmits<{ startChat: [id: EmployeeId] }>();
const { t } = useI18n(); const selected = ref<EmployeeId | null>(null); const savingSkillId = ref<string | null>(null); const { skills, load, policyFor, setPolicy } = useCapabilities();
const selectedEmployee = computed(() => props.employees.find((employee) => employee.id === selected.value) ?? null);
onMounted(() => void load());
function mode(skillId: string): PolicyMode { return selected.value ? policyFor(selected.value, skillId)?.mode ?? 'disabled' : 'disabled'; }
async function update(skillId: string, event: Event) { if (!selected.value) return; savingSkillId.value = skillId; try { await setPolicy(selected.value, skillId, (event.target as HTMLSelectElement).value as PolicyMode); } finally { savingSkillId.value = null; } }
</script>
<template>
  <section class="mx-auto w-full max-w-6xl px-6 py-14 sm:px-12"><header class="mb-9"><p class="mb-2 text-[11px] font-extrabold tracking-[.13em] text-[var(--accent)]">OPCAI / TEAM</p><h1 class="text-4xl font-bold tracking-[-.045em]">{{ t('employee.title') }}</h1><p class="mt-3 max-w-2xl leading-relaxed text-[var(--muted)]">{{ selectedEmployee ? t('employee.detailSubtitle') : t('employee.subtitle') }}</p></header>
    <template v-if="!selectedEmployee"><div class="mb-5 flex items-center justify-between"><p class="text-sm font-semibold">{{ t('employee.directory') }}</p><p class="text-xs text-[var(--muted)]">{{ t('employee.directoryHelp') }}</p></div><div class="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><button v-for="employee in employees" :key="employee.id" class="group min-h-[190px] rounded-[18px] border border-[var(--border)] bg-[var(--surface)] p-5 text-left transition hover:-translate-y-0.5 hover:border-[var(--accent)] hover:shadow-sm" type="button" @click="selected = employee.id"><span class="grid h-12 w-12 place-items-center rounded-2xl text-[11px] font-extrabold text-white" :style="{ background: employee.color }">{{ employee.initials }}</span><div class="mt-4 flex items-center gap-2"><h2 class="text-[16px] font-bold">{{ t(employee.nameKey) }}</h2><span v-if="employee.system" class="rounded bg-[var(--accent-soft)] px-1.5 py-0.5 text-[9px] font-bold text-[var(--accent)]">{{ t('employee.system') }}</span></div><p class="mt-2 text-[13px] leading-relaxed text-[var(--muted)]">{{ t(employee.descriptionKey) }}</p><span class="mt-5 inline-block text-sm font-semibold text-[var(--accent)]">{{ t('employee.viewDetails') }} →</span></button></div></template>
    <template v-else><button class="mb-5 rounded-lg border border-[var(--border)] px-3 py-2 text-sm font-semibold text-[var(--muted)] hover:bg-[var(--surface-muted)]" type="button" @click="selected = null">← {{ t('employee.backToDirectory') }}</button><section class="rounded-[20px] border border-[var(--border)] bg-[var(--surface)] p-6"><div class="flex flex-wrap items-start justify-between gap-4"><div class="flex gap-4"><span class="grid h-14 w-14 shrink-0 place-items-center rounded-2xl text-xs font-extrabold text-white" :style="{ background: selectedEmployee.color }">{{ selectedEmployee.initials }}</span><div><div class="flex items-center gap-2"><h2 class="text-2xl font-bold">{{ t(selectedEmployee.nameKey) }}</h2><span v-if="selectedEmployee.system" class="rounded bg-[var(--accent-soft)] px-1.5 py-0.5 text-[9px] font-bold text-[var(--accent)]">{{ t('employee.system') }}</span></div><p class="mt-2 max-w-2xl text-sm leading-relaxed text-[var(--muted)]">{{ t(selectedEmployee.descriptionKey) }}</p></div></div><button class="rounded-lg bg-[var(--accent)] px-3 py-2 text-sm font-semibold text-white" type="button" @click="emit('startChat', selectedEmployee.id)">{{ t('employee.start') }}</button></div>
      <div class="mt-8 border-t border-[var(--border)] pt-6"><p class="text-[11px] font-extrabold tracking-[.12em] text-[var(--accent)]">{{ t('employee.skillPolicy') }}</p><h3 class="mt-1 text-lg font-bold">{{ t('employee.capabilityTitle') }}</h3><p class="mt-1 text-sm text-[var(--muted)]">{{ t('employee.skillPolicyHelp') }}</p>
      <div class="mt-5 rounded-xl border border-[var(--border)] bg-[var(--surface-muted)]/40 px-4 py-3"><div class="flex flex-wrap items-center justify-between gap-3"><div><strong class="text-sm">{{ t('employee.baselineSkill') }}</strong><span class="ml-2 rounded bg-[var(--accent-soft)] px-1.5 py-0.5 text-[9px] font-bold text-[var(--accent)]">{{ t('employee.system') }}</span><p class="mt-1 text-xs text-[var(--muted)]">{{ baselineWorkspaceSkillMeta.description }}</p><p class="mt-1 text-[11px] text-[var(--muted)]">{{ t('employee.baselineSkillTier') }}</p></div><span class="text-xs font-semibold text-emerald-600">{{ t('employee.baselineSkillAlways') }}</span></div></div>
      <div class="mt-3 divide-y divide-[var(--border)]"><div v-for="skill in skills" :key="skill.id" class="flex flex-wrap items-center justify-between gap-3 py-3"><div><strong class="text-sm">{{ skill.name }}</strong><p class="mt-1 text-xs text-[var(--muted)]">{{ skill.description }}</p></div><select class="rounded-lg border border-[var(--border)] bg-[var(--surface-muted)] px-2.5 py-2 text-xs" :value="mode(skill.id)" :disabled="savingSkillId === skill.id || Boolean(skill.systemOnly && selectedEmployee.id !== 'administrator')" @change="update(skill.id, $event)"><option value="disabled">{{ t('employee.skillDisabled') }}</option><option value="available">{{ t('employee.skillAvailable') }}</option><option value="default">{{ t('employee.skillDefault') }}</option></select></div></div></div>
    </section></template>
  </section>
</template>
